---
# This file can be renamed as `docker-compose.override.yaml` and uncomment the desired lines for
# development. The file `docker-compose.override.yaml` is ignored by Git by default.

# yamllint disable rule:line-length

version: '2.0'

services:
  alembic:
    volumes:
      # For Python project development.
      - ./geoportal/geoportailv3_geoportal:/app/geoportailv3_geoportal
  geoportal:
    user: root
    volumes:
      # For Python project development.
      - ./geoportal/geoportailv3_geoportal:/app/geoportailv3_geoportal
      # For Python c2cgeportal development.
      # - ./../c2cgeoportal/commons/c2cgeoportal_commons:/opt/c2cgeoportal/commons/c2cgeoportal_commons
      # - ./../c2cgeoportal/geoportal/c2cgeoportal_geoportal:/opt/c2cgeoportal/geoportal/c2cgeoportal_geoportal
      # - ./../c2cgeoportal/admin/c2cgeoportal_admin:/opt/c2cgeoportal/admin/c2cgeoportal_admin
    environment:
      - GUNICORN_CMD_ARGS=--reload
      - C2CWSGIUTILS_CONFIG=/app/development.ini
      # - PRINT_URL=http://print:8080/print/
    ports:
      - 5678:5678  # For remote debugging using Visual Studio Code

  # Also uncomment the PRINT_URL in geoportal
  # print:
  #   extends:
  #     file: docker-compose-lib.yaml
  #     service: print
  #   volumes_from:
  #     - config:ro

  # qgisserver:
  #   # volumes:
  #   #   - './../c2cgeoportal/docker/qgisserver/geomapfish_qgisserver/:/var/www/plugins/geomapfish_qgisserver/'
  #   #   - './../c2cgeoportal/commons/c2cgeoportal_commons:/opt/c2cgeoportal/commons/c2cgeoportal_commons/'
  #   environment:
  #     - QGIS_SERVER_LOG_LEVEL=0

  # For Javascript project development.
  # The debug application will be availavble at ``https://<host>/<entry_point>/dev/<interface>.html``.
  webpack_dev_server:
    # Uncomment these lines when you want to debug respectively the project js, ngeo js and/or the gmf contrib js.
    # Adapt the path for ngeo / gmf contrib to point where you have checkouted the code.
    # volumes:
    #   - ./geoportal/geoportailv3_geoportal/static-ngeo:/app/geoportailv3_geoportal/static-ngeo
    #   - ./../ngeo/src:/usr/lib/node_modules/ngeo/src
    #   - ./../ngeo/contribs:/usr/lib/node_modules/ngeo/contribs
    volumes_from:
      - config:rw
    extends:
      file: docker-compose-lib.yaml
      service: webpack_dev_server
    command:
      [ "webpack-dev-server", "--mode=development", "--debug", "--watch", "--progress", "--no-inline" ]
    environment:
      - CASIPO_STAGING_URL
      - PAG_OWNCLOUD_PASSWORD
      - LDAP_PASSWD
      - FAKE_REVERSE_GEOCODING=1
      - PAG_OWNCLOUD_INTERNAL_URL
      - FAKE_PRINT_URLS=http://print:8080/print/geoportailv3,http://print:8080/print/geoportailv3
      - PAG_FME_TOKEN
      - SHORTENER_BASE_URL
      - ROUTING_MAPQUEST_API_KEY
      - LOG_LEVEL=INFO
      - AUTHTKT_SECURE=false
      - CASIPO_OWNCLOUD_EXTERNAL_URL
      - LDAP_BIND
      - DB_MYMAPS
      - FAKE_CMSSEARCH=1
      - DHM_DEM_FILE=/var/luxdata/dem500.tif
      - ANF_EMAIL
      - GUNICORN_ACCESS_LOG_LEVEL=INFO
      - PGSCHEMA
      - PAG_PROD_URL
      - IGNORE_I18N_ERRORS=TRUE
      - SQL_LOG_LEVEL=INFO
      - AGE_CRUES_EMAIL
      - CASIPO_SMTP_SERVER
      - LDAP_URL
      - LDAP_FILTER_TMPL
      - PDS_BCC_ADDRESS
      - PAG_OWNCLOUD_USER
      - FAKE_FULLTEXT_SEARCH=1
      - AGE_CRUES_LAYERS
      - CASIPO_PROD_URL
      - CASIPO_OWNCLOUD_INTERNAL_URL
      - C2CGEOPORTAL_LOG_LEVEL=INFO
      - PAG_OWNCLOUD_EXTERNAL_URL
      - ANF_MAP_ID
      - ELASTIC_SERVERS
      - DB_ECADASTRE
      - DB_POI
      - CASIPO_OWNCLOUD_USER
      - DHM_DEM_TYPE=gdal
      - PAG_STAGING_URL
      - PDS_PROD_URL
      - CASIPO_BCC_ADDRESS
      - AGE_CRUES_SHOW_LINK
      - SHORTENER_ALLOWED_HOST
      - DEBUG_TOOLBAR=1
      - GUNICORN_LOG_LEVEL=INFO
      - AGE_CRUES_ROLES
      - PDS_SMTP_SERVER
      - CASIPO_FME_TOKEN
      - FAKE_LAYERSEARCH=0
      - OTHER_LOG_LEVEL=WARN
      - CASIPO_OWNCLOUD_PASSWORD
      - PAG_SMTP_SERVER
      - DEFAULT_MYMAPS_ROLE
      - GUNICORN_PARAMS=--bind=:8080 --threads=10 --timeout=60 --reload --forwarded-allow-ips=*
      - DB_PGROUTE
      - MAILER_DIRECTORY
      - AGE_CRUES_MAP_ID
      - PDS_STAGING_URL
      - C2CWSGIUTILS_CONFIG=/app/development.ini
      - PAG_BCC_ADDRESS
      - ELASTIC_INDEX
      - LDAP_BASE_DN
      - PAG_FILE_SERVER
      - ROUTING_GRAPHHOPPER_API_KEY
      - GUNICORN_CMD_ARGS=--reload
      - VISIBLE_ENTRY_POINT
      - PACKAGE=geoportailv3
      - PGHOST
      - PGHOST_SLAVE
      - PGPORT
      - PGPORT_SLAVE
      - PGUSER
      - PGPASSWORD
      - PGDATABASE
      - PGSSLMODE
      - PGSCHEMA_STATIC
      - PGOPTIONS
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
      - AWS_S3_ENDPOINT
      - VISIBLE_WEB_HOST
      - VISIBLE_WEB_PROTOCOL
      - AUTHTKT_TIMEOUT
      - AUTHTKT_REISSUE_TIME
      - AUTHTKT_MAXAGE
      - AUTHTKT_SECRET
      - AUTHTKT_COOKIENAME
      - AUTHTKT_HTTP_ONLY
      - AUTHTKT_SAMESITE
      - BASICAUTH
      - TINYOWS_URL
      - MAPSERVER_URL
      - QGISSERVER_URL
      - PRINT_URL
      - DEVSERVER_HOST
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_DB
      - C2C_REDIS_URL
      - C2C_BROADCAST_PREFIX
      - C2C_LOG_VIEW_ENABLED=TRUE
      - C2C_SQL_PROFILER_ENABLED=TRUE
      - C2C_DEBUG_VIEW_ENABLED=TRUE
      - C2C_SECRET
      - C2CGEOPORTAL_LOG_LEVEL
      - SQL_LOG_LEVEL
      - DOGPILECACHE_LOG_LEVEL
      - LOG_TYPE
      - C2CWSGIUTILS_LOG_LEVEL=WARN

