---

# The project Docker compose file for development.

version: '2'

services:

  webpack-dev-server:
    image: camptocamp/geoportailv3-geoportal:latest
    volumes:
      - /home/external/workspace/geoportailv3/geoportal/geoportailv3_geoportal/static-ngeo:/app/geoportailv3_geoportal/static-ngeo
    command:
      - webpack-dev-server
      - --mode=development
      - --host=webpack-dev-server
      - --port=8080
      - --debug
      - --watch
      - --progress
    environment:
      - VISIBLE_ENTRY_POINT
      - VISIBLE_WEB_HOST
      - VISIBLE_WEB_PROTOCOL
      - DEVSERVER_HOST
      - C2C_REDIS_URL
      - INTERFACE=main
