---

version: 1
update_configs:
  - package_manager: javascript
    directory: /
    update_schedule: live
    automerged_updates:
      - match:
          update_type: all
  - package_manager: javascript
    directory: /
    update_schedule: live
    automerged_updates:
      - match:
          update_type: all
    target_branch: "2.4"
    allowed_updates:
      - match:
          update_type: security

  - package_manager: python
    directory: /
    update_schedule: live
    allowed_updates:
      - match:
          dependency_type: direct
    automerged_updates:
      - match:
          update_type: all
    ignored_updates:
      - match:
          dependency_name: none
  - package_manager: python
    directory: /
    update_schedule: live
    target_branch: "2.4"
    allowed_updates:
      - match:
          update_type: security
